package dev.kuku.knodeledge.services.ai.internal.models;

import java.util.List;

/**
 * Data Transfer Objects for the Knowledge Graph extraction.
 *
 * <h2>Conditional Preferences — Hybrid Schema</h2>
 * <p>Edges can carry a {@code conditions} list of node IDs to represent qualified
 * relationships (e.g. "dislikes ice cream <em>when it contains dry fruit</em>").</p>
 *
 * <p>The hybrid approach stores conditions in two complementary ways:</p>
 * <ol>
 *   <li><strong>On the edge</strong> as {@code conditions: List<String>} (node IDs) — for fast
 *       serialized retrieval and LLM context.</li>
 *   <li><strong>As a {@code CONDITIONED_BY} edge</strong> auto-generated by {@code LLMAIService} —
 *       enabling proper graph traversal without string matching.</li>
 * </ol>
 *
 * <p>Unconditional edges use {@code conditions = []} (empty list).<br>
 * Conditional edges coexist with unconditional ones — they are never superseded by each other.
 * See {@code LLMAIService.isSuperseded()} and {@code docs/conditional-preferences-schema.md}.</p>
 */
public class GraphDto {

    public record NodeDto(
        String id,
        String label,
        List<String> categories,
        String description
    ) {}

    /**
     * A persisted edge in the knowledge graph.
     *
     * @param source     Source node ID
     * @param target     Target node ID
     * @param predicate  Relationship type (e.g. LIKES, DISLIKES, CONDITIONED_BY)
     * @param context    The original sentence that produced this edge
     * @param conditions Node IDs that qualify this relationship (empty = unconditional).
     *                   e.g. for "dislikes ice cream when it contains dry fruit",
     *                   conditions = ["dry_fruit"]. A CONDITIONED_BY edge to each
     *                   condition node is auto-generated by LLMAIService.
     */
    public record EdgeDto(
        String source,
        String target,
        String predicate,
        String context,
        List<String> conditions
    ) {}

    public record GraphResponse(
        List<NodeDto> nodes,
        List<EdgeDto> edges
    ) {}

    public record ExtractedNodeDto(
        String id,
        String label,
        List<String> categories,
        String description,
        String confidence // HIGH, MEDIUM, LOW
    ) {}

    /**
     * An edge extracted by the LLM during ingestion, before merging into the graph.
     *
     * @param source       Source node ID
     * @param target       Target node ID
     * @param predicate    Relationship type (e.g. LIKES, DISLIKES, WATCHED)
     * @param taxonomyType Edge category: EVENT, PREFERENCE, or STATE
     * @param confidence   Extraction confidence: HIGH, MEDIUM, or LOW
     * @param context      The cleaned sentence this edge was extracted from
     * @param conditions   Node IDs qualifying this relationship (empty = unconditional).
     *                     When non-empty, LLMAIService will also auto-create a
     *                     CONDITIONED_BY edge from source to each condition node.
     */
    public record ExtractedEdgeDto(
        String source,
        String target,
        String predicate,
        String taxonomyType, // EVENT, PREFERENCE, STATE
        String confidence,   // HIGH, MEDIUM, LOW
        String context,      // The raw sentence context
        List<String> conditions  // node IDs that qualify this edge; empty = unconditional
    ) {}

    public record IngestionResponse(
        List<ExtractedNodeDto> nodes,
        List<ExtractedEdgeDto> edges
    ) {}

    public record VerificationResponse(
        boolean linterApproved,
        List<String> hallucinatedTriples,
        List<String> missingFacts,
        String reasoning
    ) {}
}
